NumberOfEccentricities=[1 2 3 4 5 6 7 8 9 10]; %Sample cells at each eccentricity
NumberOfCells=linspace(1,1000,1000); %How many cells per sample?
for e=1:length(NumberOfEccentricities)
    EccentricityLabel=strcat('Ecc',num2str(NumberOfEccentricities(e)),'mm');
    Coords=[];
    for c=1:length(NumberOfCells)
        [cnAll,snAll,cpAll,spAll]=RandomizeConeInputs_Gauss1(e);
        Coords(c,:)=[cpAll(1) spAll(1)];
    end
    Data.(matlab.lang.makeValidName(EccentricityLabel))=Coords;
end

figure;
hold on;
xlabel('Center L/(L+M)');
ylabel('Center L/(L+M)'); 
axis([0 1 0 1]);
axis square
EccMarkers=['o' 'd' '^' 'v' '<' '>' 's' 'p' 'h' '*'];

for e=1:length(NumberOfEccentricities)
    EccentricityLabel=strcat('Ecc',num2str(NumberOfEccentricities(e)),'mm');
    for c=1:length(NumberOfCells)
        PlotCenterWeight=Data.(matlab.lang.makeValidName(EccentricityLabel))(c,1);
        PlotSurroundWeight=Data.(matlab.lang.makeValidName(EccentricityLabel))(c,2);
        Plot=plot(PlotCenterWeight,PlotSurroundWeight,'ro');
        set(Plot,...
            'LineStyle','none',...
            'Color','k',...
            'MarkerFaceColor',[0.5 0.5 0.5],...
            'MarkerSize',8,...
            'Marker',EccMarkers(e))
    end
end


for e=1:length(NumberOfEccentricities)
    EccentricityLabel=strcat('Ecc',num2str(NumberOfEccentricities(e)),'mm');
    for c=1:length(NumberOfCells)
        hist(Data.(matlab.lang.makeValidName(EccentricityLabel))(:,1))
        PlotSurroundWeight=Data.(matlab.lang.makeValidName(EccentricityLabel))(c,2);
        Plot=plot(PlotCenterWeight,PlotSurroundWeight,'ro');
        set(Plot,...
            'LineStyle','none',...
            'Color','k',...
            'MarkerFaceColor',[0.5 0.5 0.5],...
            'MarkerSize',8,...
            'Marker',EccMarkers(e))
    end
end

% sHist=[Data.Ecc1mm(:,2);...
% Data.Ecc2mm(:,2);...
% Data.Ecc3mm(:,2);...
% Data.Ecc4mm(:,2);...
% Data.Ecc5mm(:,2);...
% Data.Ecc6mm(:,2);...
% Data.Ecc7mm(:,2);...
% Data.Ecc8mm(:,2);...
% Data.Ecc9mm(:,2);...
% Data.Ecc10mm(:,2);]
